# Generated by Django 3.1.2 on 2020-10-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employed',
            name='cvitae',
            field=models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='employed',
            name='gender',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employed',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
