# Generated by Django 3.1.2 on 2020-10-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20201013_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employed',
            name='gender',
        ),
    ]
