# Generated by Django 3.1.2 on 2020-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_employed_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employed',
            name='gender',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
